version: '3.3'
services:
  postgres:
    image: postgres:12
    env_file: .env
    restart: on-failure
    volumes:
    - db_data_hasura:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:latest.cli-migrations-v3
    ports:
    - 4780:8080
    depends_on:
    - "postgres"
    - "nextjs"
    restart: on-failure
    env_file:
      - .env
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: ${DB_URL}
      HASURA_GRAPHQL_DATABASE_URL: ${DB_URL}
      PG_DATABASE_URL: ${DB_URL}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
    volumes:
      - ./hasura-server/migrations:/hasura-migrations
      - ./hasura-server/metadata:/hasura-metadata
      - ./hasura-server/seeds:/hasura-seeds
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: yarn dev
    ports:
      - ${CLIENT_PORT}:3000
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
volumes:
  db_data_hasura:
